- name: feature 
  color: "6663ed"
  aliases: []
- name: fix 
  color: "f97f3c"
  aliases: []
- name: test 
  color: "98eab1"
  aliases: []
- name: document 
  color: "c7e5f2"
  aliases: []
- name: chore 
  color: "aff1e4"
  aliases: []
- name: lint 
  color: "c0f1af"
  aliases: []
- name: refactor 
  color: "eea4f3"
  aliases: []
- name: hotfix 
  color: "f70808"
  aliases: []
