name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
template: |
  # What's Changed
  $CHANGES
categories:
  - title: '🚀 New Feature'
    label: 'feature'
  - title: '🧨: Document'
    label: 'document'
  - title: '🐛 Bug Fixes'
    label: 'fix'
  - title: 'Hot Fixes'
    label: 'hotfix'
  - title: 'Chore'
    label: 'chore'
  - title: '⚒️ MRefactor'
    label: 'refactor'
  - title: '📈 Lint'
    label: 'lint'
